/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 09 19:33:45 GMT 2025
 */

package examples;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import examples.KruskalAlgorithm;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KruskalAlgorithm_ESTest extends KruskalAlgorithm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        KruskalAlgorithm.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      KruskalAlgorithm kruskalAlgorithm0 = new KruskalAlgorithm((-1090), 2637);
      KruskalAlgorithm.Subset[] kruskalAlgorithm_SubsetArray0 = new KruskalAlgorithm.Subset[3];
      KruskalAlgorithm.Subset kruskalAlgorithm_Subset0 = kruskalAlgorithm0.new Subset();
      kruskalAlgorithm_SubsetArray0[0] = kruskalAlgorithm_Subset0;
      kruskalAlgorithm_SubsetArray0[1] = kruskalAlgorithm_Subset0;
      kruskalAlgorithm0.performUnion(kruskalAlgorithm_SubsetArray0, 1, 1);
      assertEquals(2637, kruskalAlgorithm0.edges);
      assertEquals((-1090), kruskalAlgorithm0.vertices);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      KruskalAlgorithm kruskalAlgorithm0 = new KruskalAlgorithm(0, 0);
      kruskalAlgorithm0.applyKruskal();
      assertEquals(0, kruskalAlgorithm0.vertices);
      assertEquals(0, kruskalAlgorithm0.edges);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      KruskalAlgorithm kruskalAlgorithm0 = new KruskalAlgorithm(1967, 2004);
      // Undeclared exception!
      try { 
        kruskalAlgorithm0.applyKruskal();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2004
         //
         verifyException("examples.KruskalAlgorithm", e);
      }
  }
}
