/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 25 15:25:12 GMT 2023
 */

package game;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import game.PitestResults;
import game.PitestResultsParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PitestResultsParser_ESTest extends PitestResultsParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PitestResults pitestResults0 = PitestResultsParser.parseResults("");
      assertEquals(0, pitestResults0.getSurvivedMutants());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        PitestResultsParser.parseResults((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PitestResultsParser pitestResultsParser0 = new PitestResultsParser();
  }
}
